name: Test on pull_request

on:
  pull_request:
    branches: [master]

jobs:
  teste:
    name: Test infra on pull_request
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: us-east-1
    
    - name: Build Lambda Package
      run: |
        sh scripts/build_lambda_package.sh

    - name: IaC Test
      env:
        COMMAND_IAC: terraform
      run: |
        cd infrastructure
        $COMMAND_IAC init
        $COMMAND_IAC fmt
        $COMMAND_IAC validate
        $COMMAND_IAC plan